### ISSUE TITLE
Using `bubblewrap` breaks Darwin compatibility

### ISSUE THREAD

**Issue by uncenter** [Gerg-L/mnw#1]
The `bubblewrap` package added here in https://github.com/Gerg-L/mnw/commit/8d5af5289aeb8c177ad746ca7d5c835c59b03057 [does not support Darwin](https://github.com/NixOS/nixpkgs/blob/c865becfbe458e3418f217898454d310192a76af/pkgs/tools/admin/bubblewrap/default.nix#L53) and therefore mnw no longer builds on Darwin machines. This breaks Darwin support for https://github.com/NotAShelf/nvf upstream, where the flake.lock was updated to include this change in [NotAShelf/nvf@`37dbdbb` (#353)](https://github.com/NotAShelf/nvf/pull/353/commits/37dbdbb06d4d99297ee94adf6733893242b979c7).

**Comment by Gerg-L** [comment]
Ahhhhh, i didn't even think about darwin.
Well, nvf's mnw input should be pinned before that change while I figure out an alternative solution

**Comment by uncenter** [comment]
> Well, nvf's mnw input should be pinned before that change while I figure out an alternative solution

You updated it yesterday in nvf (commit linked above) so this change is affecting nvf Darwin users who have updated the nvf input. Thanks for looking into it :)

**Comment by Gerg-L** [comment]
https://github.com/NotAShelf/nvf/commit/fd90cf7fd5c0457d9ceece133832aac924f48118
Fixed in nvf for now

**Comment by uncenter** [comment]
Great thanks :)

**Comment by Gerg-L** [comment]
bubble wrap is gone
