### ISSUE TITLE
Testing configuration

### ISSUE THREAD

**Issue by viperML** [Gerg-L/mnw#2]
Would it be possible to define a custom `checkPhase` that runs neovim with its configuration, and checks that no error was thrown during startup?

**Comment by Gerg-L** [comment]
For your own configuration?
Or in this repo

**Comment by viperML** [comment]
I mean that mnw would provide a checkPhase like that by itself.

**Comment by Gerg-L** [comment]
I don't know of a way to provide a generic test which will work in any meaningful way with anybody's neovim config
