### ISSUE TITLE
Help tags broken

### ISSUE THREAD

**Issue by Nxllpointer** [Gerg-L/mnw#5]
Hi,
Commit https://github.com/Gerg-L/mnw/commit/00ccbc83e83694b07005e8f9273ca8557e5f20ae seems to have broken help tags. I suspect this is because the packdir itself is not added to the runtimepath anymore, which contains the doc/tags file. Simply adding the packdir makes nvim able to find tags again for me:
`:lua vim.opt.rtp:append("/nix/store/m12bw21ibsb79s52zmz0ch5d6cr00mz1-neovim-pack-dir")`
I can reproduce this bug when using mnw directly and through nvf.

Try it yourself:
`nix run github:NotAShelf/nvf --override-input mnw "github:Greg-L/mnw?rev=8e80e53d4aa1a651fb1d8bd32aa7809833870d15"`
-> Can find lspconfig tag
`nix run github:NotAShelf/nvf --override-input mnw "github:Greg-L/mnw?rev=00ccbc83e83694b07005e8f9273ca8557e5f20ae"`
-> Can not find lspconfig tag

**Comment by Gerg-L** [comment]
ah, i knew of this issue with nvf but I thought nvf was on a newer mnw version and that the issue was something else
fixed in last commit

**Comment by Nxllpointer** [comment]
Thank you ❤️
