### ISSUE TITLE
Error on build: neovim-node-client doesn't exist

### ISSUE THREAD

**Issue by DamitusThyYeetus123** [Gerg-L/mnw#6]
Due to how new neovim-node-client is on nixpkgs, it simply does not exist for a large chunk of systems. I would personally not use it, or add a failsafe, until at minimum the package is in a stable release.

Full error:
lib.customisation.callPackageWith: Function called without required argument "neovim-node-client" at /nix/store/niaq0axr15cm1dh6w4h8hwr1nplir1as-source/wrapper.nix:4

**Comment by Gerg-L** [comment]
it was renamed https://github.com/NixOS/nixpkgs/commit/159c8401016a50fcbd6aece36eeb3e6a8948b039
either set `useNodeJS` to false,
 use a older mnw rev like 5fe5c41975ed0af55f55dc37cd28ba906a5d015e,
 or use a nixpkgs commit after the above linked nixpkgs commit

**Comment by Gerg-L** [comment]
attempting to fix in 24.11 with this backport https://github.com/NixOS/nixpkgs/pull/361286.
otherwise i'll have to fix it with a check

**Comment by Gerg-L** [comment]
backport merged, i'm gonna make a tag for pre-24.11 usage
